DROP TABLE IF EXISTS ticket_number_sequence;
ALTER TABLE ticket_tag DROP CONSTRAINT IF EXISTS fk_ticket_tag_ticket_id;
DROP TRIGGER IF EXISTS trg_ticket_nesting_depth ON ticket;
DROP FUNCTION IF EXISTS check_ticket_nesting_depth();
DROP INDEX IF EXISTS idx_ticket_due_date;
DROP INDEX IF EXISTS idx_ticket_priority;
DROP INDEX IF EXISTS idx_ticket_created_by_id;
DROP INDEX IF EXISTS idx_ticket_assigned_to_id;
DROP INDEX IF EXISTS idx_ticket_customer_id;
DROP INDEX IF EXISTS idx_ticket_parent_ticket_id;
DROP INDEX IF EXISTS idx_ticket_status_id;
DROP INDEX IF EXISTS idx_ticket_ticket_type_id;
DROP INDEX IF EXISTS idx_ticket_space_id;
DROP INDEX IF EXISTS idx_ticket_number;
DROP TABLE IF EXISTS ticket;
